In [1]:
"""Analyze."""
import numpy as np
import pickle
import matplotlib.pyplot as plt
%matplotlib notebook


class ReducedSystem:
    """Reduced system only containing box size and averaged energies."""

    def __init__(self, mean_box, mean_en, std_en, err_en, dil, tot):
        """Initialize."""
        self.ener = mean_en
        self.std = std_en
        self.err = err_en
        self.box = mean_box
        self.dil = dil
        self.tot = tot
        self.phi = dil/tot

In [2]:
%matplotlib notebook

In [3]:
path_0a = '/net/storage/zendehroud/honey_big_highres/16x32_d0_100_a.pkl'
with open(path_0a, 'rb') as inputs:
    obj_0a = pickle.load(inputs)

In [4]:
obj_0a.box[:, 1], obj_0a.ener[:]

(array([24.  , 24.15, 24.3 , 24.45, 24.6 , 24.75, 24.9 , 25.05, 25.2 ,
        25.35, 25.5 , 25.65, 25.8 , 25.95, 26.1 , 26.25, 26.4 ]),
 array([2.67374543e-28, 3.77325598e-03, 1.51846207e-02, 3.43683601e-02,
        6.14547089e-02, 9.65700388e-02, 1.39837018e-01, 1.91374764e-01,
        2.51298986e-01, 3.19722122e-01, 3.96753469e-01, 4.82499306e-01,
        5.77063013e-01, 6.80545179e-01, 7.93043712e-01, 9.14653938e-01,
        1.04546870e+00]))

In [16]:
delta_x = obj_0a.box[1, 1] - obj_0a.box[0, 1]
print(delta_x)

0.15000000000004476


In [21]:
[(obj_0a.ener[i+2]-obj_0a.ener[i])/(2*delta_x) for i in range(0, 15)]

[0.050615402271577806,
 0.10198368042773213,
 0.15423362747443306,
 0.20733892903639833,
 0.26127436463438486,
 0.3160157516738996,
 0.3715398926394777,
 0.42782452531262033,
 0.4848482758389942,
 0.5425906144777534,
 0.6010318138758634,
 0.6601529097129106,
 0.7199356635750762,
 0.7803625279259218,
 0.8414166130430598]

In [26]:
np.gradient(obj_0a.ener[:3], edge_order=2)

array([-4.57983757e-05,  7.59231034e-03,  1.52304191e-02])

In [23]:
(obj_0a.ener[1] - obj_0a.ener[0]) / delta_x

0.02515503988343695

In [24]:
(obj_0a.ener[2] - obj_0a.ener[0]) / (2*delta_x)

0.050615402271577806

In [25]:
(obj_0a.ener[3] - obj_0a.ener[1]) / (2*delta_x)

0.10198368042773213

In [33]:
y = np.array([1, 2, 4, 7, 11, 16])

In [34]:
len(y)

6

In [60]:
def grad(x, y):
    delta_x = np.array(x[1] - x[0])
    first = np.array((y[1] - y[0])) / delta_x
    middle = np.array(([y[i+2] - y[i] for i in range(0, len(y)-2)])) / (2*delta_x)
    last = np.array((y[-1] - y[-2])) / delta_x
    return np.concatenate(([first], middle, [last]))

In [61]:
grad(np.array([1, 2, 3, 4, 5, 6]), y)

array([1. , 1.5, 2.5, 3.5, 4.5, 5. ])

In [36]:
np.gradient(y)

array([1. , 1.5, 2.5, 3.5, 4.5, 5. ])